### PR TITLE
`register_api_field` is depracated, us `register_rest_field` instead.

### PR DESCRIPTION
**Pull request by willmot**
@joehoyle / @mattheu, any reason the original isn't on the `humanmade` repo? A pain having to fork just to make edits, plus we're out of date with original as Joe's fork is behind.

### CODE REVIEW

**Comment by joehoyle** [comment]
Yheah we should just move it to `humanmade`, @mattheu ok to handle that?

**Comment by mattheu** [comment]
@joe yeah I'll sort it

**Comment by willmot** [comment]
@mattheu get to this?

**Comment by mattheu** [comment]
Done: https://github.com/humanmade/modular-page-builder/

@joehoyle Is this good to just merge back into it? I see you have an outstanding PR. Shall I wait for that too?

**Comment by willmot** [comment]
Thanks!

**Comment by willmot** [comment]
@mattheu did the `rest-api-support` branch not make it over?

**Pull request merged**
